name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        echo "${{ secrets.DOCKERPW }}" | docker login -u "tarikgumus" --password-stdin
        docker image build -t tarikgumus/enjoyler31:latest .
        docker push tarikgumus/enjoyler31:latest
